hash-format = "sha256"

[[files]]
file = "config/ballotbox.toml"

[[files]]
file = "config/bobby-block-entity-allowlist.conf"

[[files]]
file = "config/bobby.conf"

[[files]]
file = "config/canary.json"

[[files]]
file = "config/crunchy_crunchy_advancements.toml"

[[files]]
file = "config/emi.css"

[[files]]
file = "config/fireblanket/fireblanket.txt"

[[files]]
file = "config/glowcase.toml"

[[files]]
file = "config/hoofprint.toml"

[[files]]
file = "config/item-descriptions.json"

[[files]]
file = "config/meret.toml"

[[files]]
file = "config/modernfix-mixins.properties"

[[files]]
file = "config/modfest_sync/behaviour.properties"

[[files]]
file = "config/modmenu.json"

[[files]]
file = "config/polymer/common.json"

[[files]]
file = "config/roles.json"

[[files]]
file = "config/snapper.json"

[[files]]
file = "config/sodium-options.json"

[[files]]
file = "config/styled-chat.json"

[[files]]
file = "config/styled-nicknames.json"

[[files]]
file = "config/styled_chat_emoji.json"

[[files]]
file = "config/styledplayerlist/config.json"

[[files]]
file = "config/styledplayerlist/styles/default.json"

[[files]]
file = "config/surveyor.toml"

[[files]]
file = "config/teabridge.json"

[[files]]
file = "config/waila/blacklist.json5"

[[files]]
file = "config/waila/waila.json5"

[[files]]
file = "config/waila/waila_plugins.json5"

[[files]]
file = "mods/area-tools.pw.toml"
metafile = true

[[files]]
file = "mods/area_lib.pw.toml"
metafile = true

[[files]]
file = "mods/armorstandeditor.pw.toml"
metafile = true

[[files]]
file = "mods/axiom-server.pw.toml"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
metafile = true

[[files]]
file = "mods/ballotbox.pw.toml"
metafile = true

[[files]]
file = "mods/cantilever.pw.toml"
metafile = true

[[files]]
file = "mods/crunchy-crunchy-advancements.pw.toml"
metafile = true

[[files]]
file = "mods/defaulted-hotkeys.pw.toml"
metafile = true

[[files]]
file = "mods/demobox.pw.toml"
metafile = true

[[files]]
file = "mods/drogstyle.pw.toml"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
metafile = true

[[files]]
file = "mods/fabrictailor.pw.toml"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
metafile = true

[[files]]
file = "mods/glowcase-2.3.0+1.21.jar"

[[files]]
file = "mods/item-descriptions.pw.toml"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
metafile = true

[[files]]
file = "mods/map-utils.pw.toml"
metafile = true

[[files]]
file = "mods/mcqoy.pw.toml"
metafile = true

[[files]]
file = "mods/meret.pw.toml"
metafile = true

[[files]]
file = "mods/modfest-role-sync.pw.toml"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
metafile = true

[[files]]
file = "mods/player-pronouns.pw.toml"
metafile = true

[[files]]
file = "mods/player-roles.pw.toml"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
metafile = true

[[files]]
file = "mods/scattered-shards.pw.toml"
metafile = true

[[files]]
file = "mods/shuttfup.pw.toml"
metafile = true

[[files]]
file = "mods/simple-resource-loader.pw.toml"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
metafile = true

[[files]]
file = "mods/spawnanywhere.pw.toml"
metafile = true

[[files]]
file = "mods/styled-chat.pw.toml"
metafile = true

[[files]]
file = "mods/styled-nicknames.pw.toml"
metafile = true

[[files]]
file = "mods/styledplayerlist.pw.toml"
metafile = true

[[files]]
file = "mods/teabridge.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit-cui.pw.toml"
metafile = true

[[files]]
file = "mods/worldedit-server.pw.toml"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
metafile = true

[[files]]
file = "options.txt"

[[files]]
file = "resources/common/required/mf_music/assets/minecraft/sounds.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/lang/en_us.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/models/item/music/dormant.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/models/item/music/prologue.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds.json"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds/music/dormant.ogg"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds/music/prologue.ogg"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds/music/stereo/dormant.ogg"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/sounds/music/stereo/prologue.ogg"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/textures/item/music/dormant.png"

[[files]]
file = "resources/common/required/mf_music/assets/modfest/textures/item/music/prologue.png"

[[files]]
file = "resources/common/required/mf_music/data/modfest/jukebox_song/dormant.json"

[[files]]
file = "resources/common/required/mf_music/data/modfest/jukebox_song/prologue.json"

[[files]]
file = "resources/common/required/mf_music/data/modfest/jukebox_song/stereo/dormant.json"

[[files]]
file = "resources/common/required/mf_music/data/modfest/jukebox_song/stereo/prologue.json"

[[files]]
file = "resources/common/required/mf_music/pack.mcmeta"

[[files]]
file = "resources/common/required/mf_music/pack.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/lang/en_us.json"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/avocado_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/avocado_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/avocado_mini_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/avocado_mini_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/banana_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/banana_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/banana_mini_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/banana_mini_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/coconut_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/coconut_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/coconut_mini_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/coconut_mini_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/dragonfruit_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/dragonfruit_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/dragonfruit_mini_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/dragonfruit_mini_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/lychee_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/lychee_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/lychee_mini_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/lychee_mini_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/mango_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/mango_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/mango_mini_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/mango_mini_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/passionfruit_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/passionfruit_front.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/passionfruit_mini_backing.png"

[[files]]
file = "resources/common/required/mf_shards/assets/modfest/textures/gui/shards/passionfruit_mini_front.png"

[[files]]
file = "resources/common/required/mf_shards/data/scattered_shards/shard_type/types.json"

[[files]]
file = "resources/common/required/mf_shards/pack.mcmeta"

[[files]]
file = "resources/datapack/required/mf_ballotbox/data/ballotbox/ballot/categories.json"

[[files]]
file = "resources/datapack/required/mf_ballotbox/data/ballotbox/ballot/options.json"

[[files]]
file = "resources/datapack/required/mf_ballotbox/pack.mcmeta"

[[files]]
file = "resources/datapack/required/mf_fireblanket/data/fireblanket/tags/block/block_interaction_restricted.json"

[[files]]
file = "resources/datapack/required/mf_fireblanket/data/fireblanket/tags/entity_type/entity_attack_restricted.json"

[[files]]
file = "resources/datapack/required/mf_fireblanket/data/fireblanket/tags/entity_type/entity_interaction_restricted.json"

[[files]]
file = "resources/datapack/required/mf_fireblanket/data/fireblanket/tags/item/item_interaction_restricted.json"

[[files]]
file = "resources/datapack/required/mf_fireblanket/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/Unsanded-1.1.1-custom.zip"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/ballotbox/textures/gui/sprites/emblem.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/ballotbox/textures/gui/sprites/emblem.png.mcmeta"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/glowcase/lang/en_us.json"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/texts/credits.json"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/texts/splashes.txt"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_0.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_1.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_2.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_3.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_4.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/background/panorama_5.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/edition.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/minecraft.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/gui/title/mojangstudios.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/minecraft/textures/misc/forcefield.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/modfest/textures/art/graphics/background-lockup.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/modfest/textures/art/graphics/lockup-transparent.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/assets/modfest/textures/art/icon/transparent-modfest.png"

[[files]]
file = "resources/resourcepack/required/mf_branding/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/font/emoji.json"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/font/icons.json"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/ace_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/agender_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/ananas_good.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/ananas_great.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/ananas_none.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/ananas_question.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/aro_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/aroace_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/bi_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/blanketcon.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/blob_waaaaa.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/demi_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/femboy_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/furry_pride.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/genderfluid_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/genderflux_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/genderqueer_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/intersex_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/lesbian_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/lil_pineapple.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/modfest.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/nb_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/neurodiversity_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/ohno.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/pan_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/pineapple.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/plural_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/queer_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/queer_prog_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/trans_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/uh.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/vincian_heart.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/whyfest.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/winnger.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/assets/modfest/textures/emoji/yeefuckinghaw.png"

[[files]]
file = "resources/resourcepack/required/mf_emoji/pack.mcmeta"

[[files]]
file = "resources/resourcepack/required/mf_emoji/styled_chat_emoji.json"

[[files]]
file = "resources/resourcepack/required/twemoji.zip"

[[files]]
file = "server-icon.png"

[[files]]
file = "server.properties"

[[files]]
file = "servers.dat"

[[files]]
file = "unsup.toml"
